@hostname = http://localhost:3333
@pullId = f85046fb-8b7f-4c99-8e8e-2274abfbf2e0
@optionId1 = "c0f5526b-4cf9-4b12-a1ab-1246cb0bf26c"
@optionId2 = "16d625fd-4aee-4932-afe2-dc1a9bc8a8c3"
# @no-cookie-jar

###
POST {{hostname}}/polls HTTP/1.1
content-type: application/json

{
    "title": "Qual o melhor framework Node.js?",
    "options": ["Fastify", "Express", "NestJS", "HapiJS"]
}

###
GET  {{hostname}}/polls/{{pullId}} HTTP/1.1

###
POST {{hostname}}/polls/{{pullId}}/votes HTTP/1.1
content-type: application/json

{
    "pollOptionId": {{optionId2}}
}